"""
Root conftest.py - sets environment variables before any imports.
This file is loaded by pytest before tests/conftest.py.
"""

import os
from pathlib import Path

import pytest

# Set environment variables BEFORE any other imports
# Credential material is generated by tests/conftest.py (no secrets in source).
os.environ["ENVIRONMENT"] = "test"
os.environ["EXPOSE_TOKENS_IN_BODY"] = "true"

# Use a separate test database
os.environ["TEST_DB_PATH"] = "/tmp/soc_copilot_test.db"  # nosec B108 - test-only path

# Ignore archived test files
collect_ignore_glob = ["tests/_archived/*"]


@pytest.fixture(scope="session", autouse=True)
def setup_test_database():
    """Setup test database before all tests and cleanup after."""
    db_path = Path("/tmp/soc_copilot_test.db")  # nosec B108 - test-only path

    # Remove old test database if exists
    if db_path.exists():
        db_path.unlink()

    yield

    # Cleanup after all tests
    if db_path.exists():
        db_path.unlink()
