/**
 * Auto-generated TypeScript types for i18n translations
 *
 * This file is automatically generated by scripts/generate_i18n_types.py
 * DO NOT EDIT MANUALLY - Run: npm run typegen:messages
 *
 * Translation keys are fully typed for type-safe usage:
 * ```ts
 * import { useTranslations } from 'next-intl';
 *
 * const t = useTranslations('common');
 * const message = t('save'); // Type-safe ✅
 * const invalid = t('invalid_key'); // Type error ❌
 * ```
 */

declare interface Messages {
  Messages: {
    actions: Actions;
    activities: Activities;
    admin: Admin;
    adminAudit: Adminaudit;
    adminDashboard: Admindashboard;
    adminSettings: Adminsettings;
    ai: Ai;
    aiAssistant: Aiassistant;
    aiCopilot: string;
    aiModels: string;
    alerts: Alerts;
    alertsPage: Alertspage;
    analytics: string;
    api: string;
    apiKeys: string;
    approvals: Approvals;
    assets: Assets;
    audit: string;
    chart: Chart;
    checking: string;
    cloudNative: Cloudnative;
    common: Common;
    configModal: Configmodal;
    correlation: Correlation;
    dashboard: string;
    definitions: Definitions;
    difficulty: Difficulty;
    dify: string;
    difyPage: Difypage;
    errors: Errors;
    history: History;
    home: Home;
    infoBox: Infobox;
    iocHunt: Iochunt;
    login: Login;
    logout: string;
    manualImport: Manualimport;
    marketplace: Marketplace;
    meta: Meta;
    mlPowered: Mlpowered;
    modal: Modal;
    model: Model;
    monitor: Monitor;
    nav: Nav;
    navigation: Navigation;
    notificationSettings: Notificationsettings;
    playbooks: Playbooks;
    queue: Queue;
    quickActions: Quickactions;
    reports: Reports;
    resources: Resources;
    runs: string;
    services: Services;
    settings: Settings;
    settingsApiKeys: Settingsapikeys;
    severity: Severity;
    sidebar: Sidebar;
    status: Status;
    statusError: string;
    statuses: Statuses;
    tabs: Tabs;
    threatHunting: Threathunting;
    threatIntel: Threatintel;
    triggers: Triggers;
    triggersPage: Triggerspage;
    ueba: Ueba;
    uebaPage: Uebapage;
    users: Users;
    welcome: Welcome;
  };
}

/**
 * Translation key type - all possible translation keys in the format "namespace.key"
 */
export type TranslationKey = `${keyof Messages}.${string}` | keyof Messages;

/**
 * Type-safe translation wrapper
 *
 * Usage:
 * ```ts
 * import { t } from '@/lib/i18n';
 *
 * // With type inference
 * const message = t('common.save'); // Fully typed
 *
 * // With parameters
 * const welcome = t('common.welcome', { name: 'John' });
 * ```
 */

import { useTranslations as useNextIntlTranslations } from "next-intl";

/**
 * Type-safe translation hook
 * @param namespace - Translation namespace (optional, defaults to root)
 * @returns Translation function
 */
export function useTranslations<N extends keyof Messages = keyof Messages>(
  namespace?: N
): (
  key: N extends keyof Messages ? keyof Messages[N] : keyof Messages,
  params?: Record<string, string | number>
) => string {
  return useNextIntlTranslations(namespace);
}

/**
 * Type-safe translation function for client-side usage
 * @param key - Translation key (fully typed)
 * @param params - Optional parameters for interpolation
 * @returns Translated string
 */
export function t<K extends TranslationKey>(
  key: K,
  params?: Record<string, string | number>
): string {
  // This is a placeholder - actual implementation requires client-side i18n setup
  return key;
}

/**
 * Get all available translation keys for a namespace
 * @param namespace - Translation namespace
 * @returns Array of translation keys
 */
export function getTranslationKeys<N extends keyof Messages>(namespace: N): (keyof Messages[N])[] {
  // Placeholder - would return actual keys
  return [];
}
