"""v1.0 full schema baseline

Revision ID: f8cd2630c457
Revises:
Create Date: 2026-08-30 10:06:02.905666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_full_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_models_is_default"), "ai_models", ["is_default"], unique=False
    )
    op.create_index(
        op.f("ix_ai_models_provider"), "ai_models", ["provider"], unique=False
    )
    op.create_table(
        "ai_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("model_id", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_tasks_status"), "ai_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_ai_tasks_task_type"), "ai_tasks", ["task_type"], unique=False
    )
    op.create_index(op.f("ix_ai_tasks_user_id"), "ai_tasks", ["user_id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("hostname", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("business", sa.String(), nullable=True),
        sa.Column("criticality", sa.String(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assets_deleted_at"), "assets", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_assets_hostname"), "assets", ["hostname"], unique=True)
    op.create_index(op.f("ix_assets_ip"), "assets", ["ip"], unique=True)
    op.create_table(
        "blocked_ips",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("alert_id", sa.String(length=100), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.Column("deactivated_by", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_blocked_ip_active_created",
        "blocked_ips",
        ["is_active", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_blocked_ip_value_type", "blocked_ips", ["value", "type"], unique=False
    )
    op.create_index(
        op.f("ix_blocked_ips_alert_id"), "blocked_ips", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_blocked_ips_is_active"), "blocked_ips", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_blocked_ips_value"), "blocked_ips", ["value"], unique=False
    )
    op.create_table(
        "correlation_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("time_window_seconds", sa.Integer(), nullable=False),
        sa.Column("entity_types", sa.JSON(), nullable=False),
        sa.Column("min_similarity", sa.Float(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("action_params", sa.JSON(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("group_by_field", sa.String(length=100), nullable=True),
        sa.Column("total_correlations", sa.Integer(), nullable=False),
        sa.Column("last_triggered", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_correlation_rules_enabled_priority",
        "correlation_rules",
        ["enabled", "priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlation_rules_name"), "correlation_rules", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_correlation_rules_tenant_id"),
        "correlation_rules",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "event_similarities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id_1", sa.String(length=100), nullable=False),
        sa.Column("event_id_2", sa.String(length=100), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_event_similarities_created_at",
        "event_similarities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_event_similarities_event_pair",
        "event_similarities",
        ["event_id_1", "event_id_2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_similarities_created_at"),
        "event_similarities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_similarities_event_id_1"),
        "event_similarities",
        ["event_id_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_similarities_event_id_2"),
        "event_similarities",
        ["event_id_2"],
        unique=False,
    )
    op.create_table(
        "history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_text", sa.String(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("output_markdown", sa.String(), nullable=True),
        sa.Column("extracted_iocs", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=50), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("primary_asset_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_history_created_at"), "history", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_history_module"), "history", ["module"], unique=False)
    op.create_index(
        op.f("ix_history_primary_asset_id"),
        "history",
        ["primary_asset_id"],
        unique=False,
    )
    op.create_table(
        "monitor_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("memory_percent", sa.Float(), nullable=False),
        sa.Column("memory_used_gb", sa.Float(), nullable=False),
        sa.Column("memory_total_gb", sa.Float(), nullable=False),
        sa.Column("disk_percent", sa.Float(), nullable=False),
        sa.Column("disk_used_gb", sa.Float(), nullable=False),
        sa.Column("disk_total_gb", sa.Float(), nullable=False),
        sa.Column("services", sa.JSON(), nullable=False),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column("error_rate", sa.Float(), nullable=False),
        sa.Column("avg_response_time_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_monitor_history_timestamp", "monitor_history", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_monitor_history_timestamp"),
        "monitor_history",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "on_call_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotation_group", sa.String(length=64), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_on_call_active_window",
        "on_call_schedules",
        ["rotation_group", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_on_call_schedules_end_date"),
        "on_call_schedules",
        ["end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_on_call_schedules_rotation_group"),
        "on_call_schedules",
        ["rotation_group"],
        unique=False,
    )
    op.create_index(
        op.f("ix_on_call_schedules_start_date"),
        "on_call_schedules",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_on_call_schedules_user_id"),
        "on_call_schedules",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_on_call_user_window",
        "on_call_schedules",
        ["user_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permissions_action"), "permissions", ["action"], unique=False
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_index(
        op.f("ix_permissions_resource"), "permissions", ["resource"], unique=False
    )
    op.create_index(
        "ix_permissions_resource_action",
        "permissions",
        ["resource", "action"],
        unique=False,
    )
    op.create_table(
        "playbook_outputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("history_id", sa.String(length=36), nullable=True),
        sa.Column("output_type", sa.String(length=20), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=50), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_outputs_created_at"),
        "playbook_outputs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_outputs_history_id"),
        "playbook_outputs",
        ["history_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_outputs_output_type"),
        "playbook_outputs",
        ["output_type"],
        unique=False,
    )
    op.create_table(
        "prompt_registry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "version", "environment", name="uq_prompt_name_ver_env"
        ),
    )
    op.create_index(
        "ix_prompt_env_active",
        "prompt_registry",
        ["environment", "is_active", "name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_registry_environment"),
        "prompt_registry",
        ["environment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_registry_is_active"),
        "prompt_registry",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_registry_name"), "prompt_registry", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_registry_version"), "prompt_registry", ["version"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "root_cause_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.String(length=100), nullable=False),
        sa.Column("root_cause_category", sa.String(length=50), nullable=False),
        sa.Column("root_cause_subcategory", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning_steps", sa.JSON(), nullable=False),
        sa.Column("evidence_chain", sa.JSON(), nullable=False),
        sa.Column("verification_steps", sa.JSON(), nullable=False),
        sa.Column("suggested_remediation", sa.Text(), nullable=True),
        sa.Column("remediation_priority", sa.String(length=20), nullable=False),
        sa.Column("similar_alerts", sa.JSON(), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=False),
        sa.Column("ai_prompt_version", sa.String(length=50), nullable=True),
        sa.Column("analysis_duration_ms", sa.Float(), nullable=True),
        sa.Column("human_verified", sa.String(length=10), nullable=False),
        sa.Column("human_feedback", sa.Text(), nullable=True),
        sa.Column("feedback_category", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("updated_at", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_root_cause_alert_id", "root_cause_analyses", ["alert_id"], unique=False
    )
    op.create_index(
        "idx_root_cause_category",
        "root_cause_analyses",
        ["root_cause_category"],
        unique=False,
    )
    op.create_index(
        "idx_root_cause_confidence", "root_cause_analyses", ["confidence"], unique=False
    )
    op.create_index(
        op.f("ix_root_cause_analyses_alert_id"),
        "root_cause_analyses",
        ["alert_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_root_cause_analyses_root_cause_category"),
        "root_cause_analyses",
        ["root_cause_category"],
        unique=False,
    )
    op.create_table(
        "security_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_ip", sa.String(length=50), nullable=True),
        sa.Column("destination_ip", sa.String(length=50), nullable=True),
        sa.Column("protocol", sa.String(length=20), nullable=True),
        sa.Column("agent_name", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=50), nullable=True),
        sa.Column("agent_ip", sa.String(length=50), nullable=True),
        sa.Column("rule_id", sa.String(length=100), nullable=True),
        sa.Column("rule_level", sa.Integer(), nullable=True),
        sa.Column("rule_groups", sa.Text(), nullable=True),
        sa.Column("rule_mitre", sa.Text(), nullable=True),
        sa.Column("full_log", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("geoip", sa.JSON(), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("escalated_to", sa.String(length=255), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("threat_score", sa.Integer(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("iocs", sa.JSON(), nullable=True),
        sa.Column("mitre_tactics", sa.JSON(), nullable=True),
        sa.Column("mitre_techniques", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("classification", sa.String(length=50), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column("aggregated_count", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_aggregated", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_alerts_agent_name"),
        "security_alerts",
        ["agent_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_assigned_to"),
        "security_alerts",
        ["assigned_to"],
        unique=False,
    )
    op.create_index(
        "ix_security_alerts_created_at", "security_alerts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_security_alerts_deleted_at"),
        "security_alerts",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_event_timestamp"),
        "security_alerts",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_event_type"),
        "security_alerts",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_external_event_id"),
        "security_alerts",
        ["external_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_fingerprint"),
        "security_alerts",
        ["fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_id"), "security_alerts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_security_alerts_severity"),
        "security_alerts",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_security_alerts_severity_status",
        "security_alerts",
        ["severity", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_source"), "security_alerts", ["source"], unique=False
    )
    op.create_index(
        "ix_security_alerts_source_event_id",
        "security_alerts",
        ["source", "external_event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_security_alerts_source_ip"),
        "security_alerts",
        ["source_ip"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_alerts_status"), "security_alerts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_security_alerts_tenant_id"),
        "security_alerts",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "security_vulnerabilities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "CRITICAL",
                "HIGH",
                "MEDIUM",
                "LOW",
                "INFO",
                name="vulnerabilityseverity",
            ),
            nullable=False,
        ),
        sa.Column(
            "vulnerability_type",
            sa.Enum(
                "SQL_INJECTION",
                "XSS",
                "CSRF",
                "AUTHENTICATION_BYPASS",
                "AUTHORIZATION_ISSUE",
                "INSECURE_DIRECT_OBJECT_REFERENCE",
                "SENSITIVE_DATA_EXPOSURE",
                "XML_EXTERNAL_ENTITY",
                "INSECURE_DESERIALIZATION",
                "USE_OF_COMPONENT_WITH_KNOWN_VULNERABILITIES",
                "LOGGING_ISSUE",
                "OTHER",
                name="vulnerabilitytype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "REPORTED",
                "TRIAGED",
                "IN_PROGRESS",
                "FIXED",
                "VERIFIED",
                "CLOSED",
                "FALSE_POSITIVE",
                name="vulnerabilitystatus",
            ),
            nullable=False,
        ),
        sa.Column("affected_component", sa.String(length=128), nullable=False),
        sa.Column("affected_version", sa.String(length=64), nullable=True),
        sa.Column("attack_vector", sa.Text(), nullable=True),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("reproduction_steps", sa.Text(), nullable=True),
        sa.Column("fix_recommendation", sa.Text(), nullable=True),
        sa.Column("fix_implementation", sa.Text(), nullable=True),
        sa.Column("reporter", sa.String(length=128), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("in_progress_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fixed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cve_id", sa.String(length=64), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("reference_urls", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.String(length=128), nullable=True),
        sa.Column("last_updated_by", sa.String(length=128), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_false_positive", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vulnerabilities_affected_component",
        "security_vulnerabilities",
        ["affected_component"],
        unique=False,
    )
    op.create_index(
        "ix_vulnerabilities_reported_at",
        "security_vulnerabilities",
        ["reported_at"],
        unique=False,
    )
    op.create_index(
        "ix_vulnerabilities_severity",
        "security_vulnerabilities",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_vulnerabilities_status",
        "security_vulnerabilities",
        ["status"],
        unique=False,
    )
    op.create_table(
        "threat_intel_cache",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("ioc_type", sa.String(), nullable=False),
        sa.Column("ioc_value", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("pulse_count", sa.Integer(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("error_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_threat_intel_cache_created_at"),
        "threat_intel_cache",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_threat_intel_cache_deleted_at"),
        "threat_intel_cache",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_threat_intel_cache_expires_at"),
        "threat_intel_cache",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_threat_intel_cache_ioc_type"),
        "threat_intel_cache",
        ["ioc_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_threat_intel_cache_ioc_value"),
        "threat_intel_cache",
        ["ioc_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_threat_intel_cache_provider"),
        "threat_intel_cache",
        ["provider"],
        unique=False,
    )
    op.create_index(
        "ix_ti_provider_ioc",
        "threat_intel_cache",
        ["provider", "ioc_type", "ioc_value"],
        unique=True,
    )
    op.create_table(
        "ueba_baselines",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("model_data", sa.LargeBinary(), nullable=True),
        sa.Column("features_json", sa.Text(), nullable=True),
        sa.Column("anomaly_threshold", sa.Float(), nullable=True),
        sa.Column("training_samples", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ueba_baselines_user_id"), "ueba_baselines", ["user_id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_history", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(
        "ix_users_role_is_active", "users", ["role", "is_active"], unique=False
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "ai_user_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("default_model_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_user_settings_user_id"),
        "ai_user_settings",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "alert_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["security_alerts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_notes_alert_id"), "alert_notes", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_notes_user_id"), "alert_notes", ["user_id"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=255), nullable=False),
        sa.Column("last_used_at", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_keys_created_at"), "api_keys", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("extra_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_path"), "audit_logs", ["path"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_status_code"), "audit_logs", ["status_code"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("assigned_to", sa.String(length=36), nullable=True),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cases_assigned_to"), "cases", ["assigned_to"], unique=False
    )
    op.create_index("ix_cases_created_at", "cases", ["created_at"], unique=False)
    op.create_index(op.f("ix_cases_deleted_at"), "cases", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_cases_severity"), "cases", ["severity"], unique=False)
    op.create_index(
        "ix_cases_severity_status", "cases", ["severity", "status"], unique=False
    )
    op.create_index("ix_cases_sla_due_at", "cases", ["sla_due_at"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_index(op.f("ix_cases_tenant_id"), "cases", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_cases_title"), "cases", ["title"], unique=False)
    op.create_table(
        "correlated_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("attack_type", sa.String(length=100), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("raw_event_ids", sa.JSON(), nullable=False),
        sa.Column("raw_event_count", sa.Integer(), nullable=False),
        sa.Column("common_entities", sa.JSON(), nullable=False),
        sa.Column("first_seen", sa.String(length=50), nullable=False),
        sa.Column("last_seen", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("assigned_to", sa.String(length=100), nullable=True),
        sa.Column("tactics", sa.JSON(), nullable=True),
        sa.Column("techniques", sa.JSON(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("ai_remediation", sa.Text(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("affected_assets", sa.JSON(), nullable=True),
        sa.Column("affected_users", sa.JSON(), nullable=True),
        sa.Column("business_impact", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("updated_at", sa.String(length=50), nullable=False),
        sa.Column("resolved_at", sa.String(length=50), nullable=True),
        sa.Column("correlation_time_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["correlation_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_correlated_events_attack_type",
        "correlated_events",
        ["attack_type"],
        unique=False,
    )
    op.create_index(
        "idx_correlated_events_first_seen",
        "correlated_events",
        ["first_seen"],
        unique=False,
    )
    op.create_index(
        "idx_correlated_events_status_severity",
        "correlated_events",
        ["status", "severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlated_events_attack_type"),
        "correlated_events",
        ["attack_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlated_events_first_seen"),
        "correlated_events",
        ["first_seen"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlated_events_rule_id"),
        "correlated_events",
        ["rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlated_events_severity"),
        "correlated_events",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correlated_events_status"),
        "correlated_events",
        ["status"],
        unique=False,
    )
    op.create_table(
        "ioc_hits",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("history_id", sa.String(), nullable=True),
        sa.Column("asset_id", sa.String(), nullable=True),
        sa.Column("ioc_type", sa.String(), nullable=False),
        sa.Column("ioc_value", sa.String(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["history_id"],
            ["history.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ioc_hits_asset_id"), "ioc_hits", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_ioc_hits_created_at"), "ioc_hits", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ioc_hits_history_id"), "ioc_hits", ["history_id"], unique=False
    )
    op.create_index(
        op.f("ix_ioc_hits_ioc_type"), "ioc_hits", ["ioc_type"], unique=False
    )
    op.create_index(
        op.f("ix_ioc_hits_ioc_value"), "ioc_hits", ["ioc_value"], unique=False
    )
    op.create_table(
        "playbook_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("definition_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_version_no", sa.Integer(), nullable=False),
        sa.Column("execution_engine", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_definitions_deleted_at"),
        "playbook_definitions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_definitions_is_active"),
        "playbook_definitions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_definitions_name"),
        "playbook_definitions",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_definitions_status"),
        "playbook_definitions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "secrets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("encrypted_value", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_secrets_name"), "secrets", ["name"], unique=True)
    op.create_table(
        "siem_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("log_type", sa.String(length=50), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=False),
        sa.Column("parsed_fields", sa.JSON(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["security_alerts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_siem_logs_alert_id"), "siem_logs", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_siem_logs_created_at"), "siem_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_siem_logs_tenant_id"), "siem_logs", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_siem_logs_tenant_source", "siem_logs", ["tenant_id", "source"], unique=False
    )
    op.create_index(
        "ix_siem_logs_tenant_ts", "siem_logs", ["tenant_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_siem_logs_tenant_type", "siem_logs", ["tenant_id", "log_type"], unique=False
    )
    op.create_index(
        op.f("ix_siem_logs_timestamp"), "siem_logs", ["timestamp"], unique=False
    )
    op.create_table(
        "vulnerability_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["security_vulnerabilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vulnerability_notes_created_at",
        "vulnerability_notes",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_vulnerability_notes_vulnerability_id",
        "vulnerability_notes",
        ["vulnerability_id"],
        unique=False,
    )
    op.create_table(
        "case_alerts",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("added_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["security_alerts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("case_id", "alert_id"),
    )
    op.create_index(
        "ix_case_alerts_alert_id", "case_alerts", ["alert_id"], unique=False
    )
    op.create_index("ix_case_alerts_case_id", "case_alerts", ["case_id"], unique=False)
    op.create_table(
        "case_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_case_comments_case_created",
        "case_comments",
        ["case_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_comments_case_id"), "case_comments", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_comments_deleted_at"),
        "case_comments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_comments_user_id"), "case_comments", ["user_id"], unique=False
    )
    op.create_table(
        "case_timeline_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("entry_type", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_alert_id", sa.Integer(), nullable=True),
        sa.Column("performed_by", sa.String(length=36), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_alert_id"], ["security_alerts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_case_timeline_case_type",
        "case_timeline_entries",
        ["case_id", "entry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_timeline_entries_case_id"),
        "case_timeline_entries",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_timeline_entries_deleted_at"),
        "case_timeline_entries",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_timeline_entries_entry_type"),
        "case_timeline_entries",
        ["entry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_timeline_entries_occurred_at"),
        "case_timeline_entries",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "marketplace_playbooks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column("author_name", sa.String(length=100), nullable=False),
        sa.Column("source_definition_id", sa.String(length=36), nullable=True),
        sa.Column("dag_json", sa.JSON(), nullable=False),
        sa.Column("documentation", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("rating_average", sa.Float(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("required_plugins", sa.JSON(), nullable=False),
        sa.Column("compatible_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_definition_id"], ["playbook_definitions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marketplace_playbooks_category"),
        "marketplace_playbooks",
        ["category"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_playbooks_category_status",
        "marketplace_playbooks",
        ["category", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketplace_playbooks_featured"),
        "marketplace_playbooks",
        ["featured"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketplace_playbooks_name"),
        "marketplace_playbooks",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketplace_playbooks_status"),
        "marketplace_playbooks",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_playbooks_status_featured",
        "marketplace_playbooks",
        ["status", "featured"],
        unique=False,
    )
    op.create_index(
        op.f("ix_marketplace_playbooks_verified"),
        "marketplace_playbooks",
        ["verified"],
        unique=False,
    )
    op.create_table(
        "playbook_definition_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("playbook_definition_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("dag_json", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["playbook_definition_id"], ["playbook_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_definition_versions_playbook_definition_id"),
        "playbook_definition_versions",
        ["playbook_definition_id"],
        unique=False,
    )
    op.create_table(
        "playbook_edges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=36), nullable=False),
        sa.Column("source_node_id", sa.String(length=100), nullable=False),
        sa.Column("target_node_id", sa.String(length=100), nullable=False),
        sa.Column("condition_expression", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"], ["playbook_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_edges_definition_id"),
        "playbook_edges",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_edges_source_node_id"),
        "playbook_edges",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_edges_target_node_id"),
        "playbook_edges",
        ["target_node_id"],
        unique=False,
    )
    op.create_table(
        "playbook_nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("step_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("retry_policy_json", sa.JSON(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("position_x", sa.Float(), nullable=True),
        sa.Column("position_y", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"], ["playbook_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_nodes_definition_id"),
        "playbook_nodes",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_nodes_step_id"), "playbook_nodes", ["step_id"], unique=False
    )
    op.create_table(
        "playbook_triggers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("secret", sa.String(length=100), nullable=True),
        sa.Column("cron_expr", sa.String(length=100), nullable=True),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["definition_id"], ["playbook_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_triggers_definition_id"),
        "playbook_triggers",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_triggers_is_active"),
        "playbook_triggers",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_triggers_type"), "playbook_triggers", ["type"], unique=False
    )
    op.create_table(
        "marketplace_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("playbook_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["playbook_id"], ["marketplace_playbooks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marketplace_reviews_playbook_id"),
        "marketplace_reviews",
        ["playbook_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_reviews_playbook_user",
        "marketplace_reviews",
        ["playbook_id", "user_id"],
        unique=True,
    )
    op.create_table(
        "playbook_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("playbook_name", sa.String(length=100), nullable=False),
        sa.Column("playbook_version", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("execution_mode", sa.String(length=20), nullable=False),
        sa.Column("definition_id", sa.String(length=36), nullable=True),
        sa.Column("failure_strategy", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("parent_run_id", sa.String(length=36), nullable=True),
        sa.Column("trigger_source", sa.String(length=50), nullable=False),
        sa.Column("trigger_id", sa.String(length=36), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_context_json", sa.JSON(), nullable=False),
        sa.Column("context_json", sa.JSON(), nullable=False),
        sa.Column("replay_of_run_id", sa.String(length=36), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["definition_id"], ["playbook_definitions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["replay_of_run_id"], ["playbook_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trigger_id"], ["playbook_triggers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_runs_created_by_user_id"),
        "playbook_runs",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_definition_id"),
        "playbook_runs",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_deleted_at"),
        "playbook_runs",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_engine_version"),
        "playbook_runs",
        ["engine_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_execution_mode"),
        "playbook_runs",
        ["execution_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_idempotency_key"),
        "playbook_runs",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_playbook_runs_parent_run_id"),
        "playbook_runs",
        ["parent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_playbook_name"),
        "playbook_runs",
        ["playbook_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_replay_of_run_id"),
        "playbook_runs",
        ["replay_of_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_started_at"),
        "playbook_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_status"), "playbook_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_playbook_runs_trigger_id"),
        "playbook_runs",
        ["trigger_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_runs_trigger_source"),
        "playbook_runs",
        ["trigger_source"],
        unique=False,
    )
    op.create_table(
        "playbook_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("approved_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("rejected_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("on_timeout", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["rejected_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["playbook_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playbook_node_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("node_name", sa.String(length=200), nullable=False),
        sa.Column("node_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["playbook_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_node_runs_node_id"),
        "playbook_node_runs",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_node_runs_run_id"),
        "playbook_node_runs",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_node_runs_status"),
        "playbook_node_runs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "playbook_run_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.String(length=50), nullable=False),
        sa.Column("step_name", sa.String(length=200), nullable=False),
        sa.Column("step_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("skipped_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["playbook_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_run_steps_run_id"),
        "playbook_run_steps",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_run_steps_status"),
        "playbook_run_steps",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playbook_run_steps_step_index"),
        "playbook_run_steps",
        ["step_index"],
        unique=False,
    )
    op.create_table(
        "trigger_invocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trigger_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["playbook_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["trigger_id"], ["playbook_triggers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trigger_invocations_created_at"),
        "trigger_invocations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trigger_invocations_expires_at"),
        "trigger_invocations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trigger_invocations_idempotency_key"),
        "trigger_invocations",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trigger_invocations_trigger_id"),
        "trigger_invocations",
        ["trigger_id"],
        unique=False,
    )
    op.create_table(
        "playbook_node_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("node_run_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("log_text", sa.Text(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_run_id"], ["playbook_node_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playbook_node_attempts_node_run_id"),
        "playbook_node_attempts",
        ["node_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_playbook_node_attempts_node_run_id"),
        table_name="playbook_node_attempts",
    )
    op.drop_table("playbook_node_attempts")
    op.drop_index(
        op.f("ix_trigger_invocations_trigger_id"), table_name="trigger_invocations"
    )
    op.drop_index(
        op.f("ix_trigger_invocations_idempotency_key"), table_name="trigger_invocations"
    )
    op.drop_index(
        op.f("ix_trigger_invocations_expires_at"), table_name="trigger_invocations"
    )
    op.drop_index(
        op.f("ix_trigger_invocations_created_at"), table_name="trigger_invocations"
    )
    op.drop_table("trigger_invocations")
    op.drop_index(
        op.f("ix_playbook_run_steps_step_index"), table_name="playbook_run_steps"
    )
    op.drop_index(op.f("ix_playbook_run_steps_status"), table_name="playbook_run_steps")
    op.drop_index(op.f("ix_playbook_run_steps_run_id"), table_name="playbook_run_steps")
    op.drop_table("playbook_run_steps")
    op.drop_index(op.f("ix_playbook_node_runs_status"), table_name="playbook_node_runs")
    op.drop_index(op.f("ix_playbook_node_runs_run_id"), table_name="playbook_node_runs")
    op.drop_index(
        op.f("ix_playbook_node_runs_node_id"), table_name="playbook_node_runs"
    )
    op.drop_table("playbook_node_runs")
    op.drop_table("playbook_approvals")
    op.drop_index(op.f("ix_playbook_runs_trigger_source"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_trigger_id"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_status"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_started_at"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_replay_of_run_id"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_playbook_name"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_parent_run_id"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_idempotency_key"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_execution_mode"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_engine_version"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_deleted_at"), table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_definition_id"), table_name="playbook_runs")
    op.drop_index(
        op.f("ix_playbook_runs_created_by_user_id"), table_name="playbook_runs"
    )
    op.drop_table("playbook_runs")
    op.drop_index(
        "ix_marketplace_reviews_playbook_user", table_name="marketplace_reviews"
    )
    op.drop_index(
        op.f("ix_marketplace_reviews_playbook_id"), table_name="marketplace_reviews"
    )
    op.drop_table("marketplace_reviews")
    op.drop_index(op.f("ix_playbook_triggers_type"), table_name="playbook_triggers")
    op.drop_index(
        op.f("ix_playbook_triggers_is_active"), table_name="playbook_triggers"
    )
    op.drop_index(
        op.f("ix_playbook_triggers_definition_id"), table_name="playbook_triggers"
    )
    op.drop_table("playbook_triggers")
    op.drop_index(op.f("ix_playbook_nodes_step_id"), table_name="playbook_nodes")
    op.drop_index(op.f("ix_playbook_nodes_definition_id"), table_name="playbook_nodes")
    op.drop_table("playbook_nodes")
    op.drop_index(op.f("ix_playbook_edges_target_node_id"), table_name="playbook_edges")
    op.drop_index(op.f("ix_playbook_edges_source_node_id"), table_name="playbook_edges")
    op.drop_index(op.f("ix_playbook_edges_definition_id"), table_name="playbook_edges")
    op.drop_table("playbook_edges")
    op.drop_index(
        op.f("ix_playbook_definition_versions_playbook_definition_id"),
        table_name="playbook_definition_versions",
    )
    op.drop_table("playbook_definition_versions")
    op.drop_index(
        op.f("ix_marketplace_playbooks_verified"), table_name="marketplace_playbooks"
    )
    op.drop_index(
        "ix_marketplace_playbooks_status_featured", table_name="marketplace_playbooks"
    )
    op.drop_index(
        op.f("ix_marketplace_playbooks_status"), table_name="marketplace_playbooks"
    )
    op.drop_index(
        op.f("ix_marketplace_playbooks_name"), table_name="marketplace_playbooks"
    )
    op.drop_index(
        op.f("ix_marketplace_playbooks_featured"), table_name="marketplace_playbooks"
    )
    op.drop_index(
        "ix_marketplace_playbooks_category_status", table_name="marketplace_playbooks"
    )
    op.drop_index(
        op.f("ix_marketplace_playbooks_category"), table_name="marketplace_playbooks"
    )
    op.drop_table("marketplace_playbooks")
    op.drop_index(
        op.f("ix_case_timeline_entries_occurred_at"), table_name="case_timeline_entries"
    )
    op.drop_index(
        op.f("ix_case_timeline_entries_entry_type"), table_name="case_timeline_entries"
    )
    op.drop_index(
        op.f("ix_case_timeline_entries_deleted_at"), table_name="case_timeline_entries"
    )
    op.drop_index(
        op.f("ix_case_timeline_entries_case_id"), table_name="case_timeline_entries"
    )
    op.drop_index("ix_case_timeline_case_type", table_name="case_timeline_entries")
    op.drop_table("case_timeline_entries")
    op.drop_index(op.f("ix_case_comments_user_id"), table_name="case_comments")
    op.drop_index(op.f("ix_case_comments_deleted_at"), table_name="case_comments")
    op.drop_index(op.f("ix_case_comments_case_id"), table_name="case_comments")
    op.drop_index("ix_case_comments_case_created", table_name="case_comments")
    op.drop_table("case_comments")
    op.drop_index("ix_case_alerts_case_id", table_name="case_alerts")
    op.drop_index("ix_case_alerts_alert_id", table_name="case_alerts")
    op.drop_table("case_alerts")
    op.drop_index(
        "ix_vulnerability_notes_vulnerability_id", table_name="vulnerability_notes"
    )
    op.drop_index("ix_vulnerability_notes_created_at", table_name="vulnerability_notes")
    op.drop_table("vulnerability_notes")
    op.drop_index(op.f("ix_siem_logs_timestamp"), table_name="siem_logs")
    op.drop_index("ix_siem_logs_tenant_type", table_name="siem_logs")
    op.drop_index("ix_siem_logs_tenant_ts", table_name="siem_logs")
    op.drop_index("ix_siem_logs_tenant_source", table_name="siem_logs")
    op.drop_index(op.f("ix_siem_logs_tenant_id"), table_name="siem_logs")
    op.drop_index(op.f("ix_siem_logs_created_at"), table_name="siem_logs")
    op.drop_index(op.f("ix_siem_logs_alert_id"), table_name="siem_logs")
    op.drop_table("siem_logs")
    op.drop_index(op.f("ix_secrets_name"), table_name="secrets")
    op.drop_table("secrets")
    op.drop_table("role_permissions")
    op.drop_index(
        op.f("ix_playbook_definitions_status"), table_name="playbook_definitions"
    )
    op.drop_index(
        op.f("ix_playbook_definitions_name"), table_name="playbook_definitions"
    )
    op.drop_index(
        op.f("ix_playbook_definitions_is_active"), table_name="playbook_definitions"
    )
    op.drop_index(
        op.f("ix_playbook_definitions_deleted_at"), table_name="playbook_definitions"
    )
    op.drop_table("playbook_definitions")
    op.drop_index(op.f("ix_ioc_hits_ioc_value"), table_name="ioc_hits")
    op.drop_index(op.f("ix_ioc_hits_ioc_type"), table_name="ioc_hits")
    op.drop_index(op.f("ix_ioc_hits_history_id"), table_name="ioc_hits")
    op.drop_index(op.f("ix_ioc_hits_created_at"), table_name="ioc_hits")
    op.drop_index(op.f("ix_ioc_hits_asset_id"), table_name="ioc_hits")
    op.drop_table("ioc_hits")
    op.drop_index(op.f("ix_correlated_events_status"), table_name="correlated_events")
    op.drop_index(op.f("ix_correlated_events_severity"), table_name="correlated_events")
    op.drop_index(op.f("ix_correlated_events_rule_id"), table_name="correlated_events")
    op.drop_index(
        op.f("ix_correlated_events_first_seen"), table_name="correlated_events"
    )
    op.drop_index(
        op.f("ix_correlated_events_attack_type"), table_name="correlated_events"
    )
    op.drop_index(
        "idx_correlated_events_status_severity", table_name="correlated_events"
    )
    op.drop_index("idx_correlated_events_first_seen", table_name="correlated_events")
    op.drop_index("idx_correlated_events_attack_type", table_name="correlated_events")
    op.drop_table("correlated_events")
    op.drop_index(op.f("ix_cases_title"), table_name="cases")
    op.drop_index(op.f("ix_cases_tenant_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index("ix_cases_sla_due_at", table_name="cases")
    op.drop_index("ix_cases_severity_status", table_name="cases")
    op.drop_index(op.f("ix_cases_severity"), table_name="cases")
    op.drop_index(op.f("ix_cases_deleted_at"), table_name="cases")
    op.drop_index("ix_cases_created_at", table_name="cases")
    op.drop_index(op.f("ix_cases_assigned_to"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_status_code"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_path"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_created_at"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_alert_notes_user_id"), table_name="alert_notes")
    op.drop_index(op.f("ix_alert_notes_alert_id"), table_name="alert_notes")
    op.drop_table("alert_notes")
    op.drop_index(op.f("ix_ai_user_settings_user_id"), table_name="ai_user_settings")
    op.drop_table("ai_user_settings")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index("ix_users_role_is_active", table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ueba_baselines_user_id"), table_name="ueba_baselines")
    op.drop_table("ueba_baselines")
    op.drop_index("ix_ti_provider_ioc", table_name="threat_intel_cache")
    op.drop_index(
        op.f("ix_threat_intel_cache_provider"), table_name="threat_intel_cache"
    )
    op.drop_index(
        op.f("ix_threat_intel_cache_ioc_value"), table_name="threat_intel_cache"
    )
    op.drop_index(
        op.f("ix_threat_intel_cache_ioc_type"), table_name="threat_intel_cache"
    )
    op.drop_index(
        op.f("ix_threat_intel_cache_expires_at"), table_name="threat_intel_cache"
    )
    op.drop_index(
        op.f("ix_threat_intel_cache_deleted_at"), table_name="threat_intel_cache"
    )
    op.drop_index(
        op.f("ix_threat_intel_cache_created_at"), table_name="threat_intel_cache"
    )
    op.drop_table("threat_intel_cache")
    op.drop_index("ix_vulnerabilities_status", table_name="security_vulnerabilities")
    op.drop_index("ix_vulnerabilities_severity", table_name="security_vulnerabilities")
    op.drop_index(
        "ix_vulnerabilities_reported_at", table_name="security_vulnerabilities"
    )
    op.drop_index(
        "ix_vulnerabilities_affected_component", table_name="security_vulnerabilities"
    )
    op.drop_table("security_vulnerabilities")
    op.drop_index(op.f("ix_security_alerts_tenant_id"), table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_status"), table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_source_ip"), table_name="security_alerts")
    op.drop_index("ix_security_alerts_source_event_id", table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_source"), table_name="security_alerts")
    op.drop_index("ix_security_alerts_severity_status", table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_severity"), table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_id"), table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_fingerprint"), table_name="security_alerts")
    op.drop_index(
        op.f("ix_security_alerts_external_event_id"), table_name="security_alerts"
    )
    op.drop_index(op.f("ix_security_alerts_event_type"), table_name="security_alerts")
    op.drop_index(
        op.f("ix_security_alerts_event_timestamp"), table_name="security_alerts"
    )
    op.drop_index(op.f("ix_security_alerts_deleted_at"), table_name="security_alerts")
    op.drop_index("ix_security_alerts_created_at", table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_assigned_to"), table_name="security_alerts")
    op.drop_index(op.f("ix_security_alerts_agent_name"), table_name="security_alerts")
    op.drop_table("security_alerts")
    op.drop_index(
        op.f("ix_root_cause_analyses_root_cause_category"),
        table_name="root_cause_analyses",
    )
    op.drop_index(
        op.f("ix_root_cause_analyses_alert_id"), table_name="root_cause_analyses"
    )
    op.drop_index("idx_root_cause_confidence", table_name="root_cause_analyses")
    op.drop_index("idx_root_cause_category", table_name="root_cause_analyses")
    op.drop_index("idx_root_cause_alert_id", table_name="root_cause_analyses")
    op.drop_table("root_cause_analyses")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_prompt_registry_version"), table_name="prompt_registry")
    op.drop_index(op.f("ix_prompt_registry_name"), table_name="prompt_registry")
    op.drop_index(op.f("ix_prompt_registry_is_active"), table_name="prompt_registry")
    op.drop_index(op.f("ix_prompt_registry_environment"), table_name="prompt_registry")
    op.drop_index("ix_prompt_env_active", table_name="prompt_registry")
    op.drop_table("prompt_registry")
    op.drop_index(
        op.f("ix_playbook_outputs_output_type"), table_name="playbook_outputs"
    )
    op.drop_index(op.f("ix_playbook_outputs_history_id"), table_name="playbook_outputs")
    op.drop_index(op.f("ix_playbook_outputs_created_at"), table_name="playbook_outputs")
    op.drop_table("playbook_outputs")
    op.drop_index("ix_permissions_resource_action", table_name="permissions")
    op.drop_index(op.f("ix_permissions_resource"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_action"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index("ix_on_call_user_window", table_name="on_call_schedules")
    op.drop_index(op.f("ix_on_call_schedules_user_id"), table_name="on_call_schedules")
    op.drop_index(
        op.f("ix_on_call_schedules_start_date"), table_name="on_call_schedules"
    )
    op.drop_index(
        op.f("ix_on_call_schedules_rotation_group"), table_name="on_call_schedules"
    )
    op.drop_index(op.f("ix_on_call_schedules_end_date"), table_name="on_call_schedules")
    op.drop_index("ix_on_call_active_window", table_name="on_call_schedules")
    op.drop_table("on_call_schedules")
    op.drop_index(op.f("ix_monitor_history_timestamp"), table_name="monitor_history")
    op.drop_index("idx_monitor_history_timestamp", table_name="monitor_history")
    op.drop_table("monitor_history")
    op.drop_index(op.f("ix_history_primary_asset_id"), table_name="history")
    op.drop_index(op.f("ix_history_module"), table_name="history")
    op.drop_index(op.f("ix_history_created_at"), table_name="history")
    op.drop_table("history")
    op.drop_index(
        op.f("ix_event_similarities_event_id_2"), table_name="event_similarities"
    )
    op.drop_index(
        op.f("ix_event_similarities_event_id_1"), table_name="event_similarities"
    )
    op.drop_index(
        op.f("ix_event_similarities_created_at"), table_name="event_similarities"
    )
    op.drop_index("idx_event_similarities_event_pair", table_name="event_similarities")
    op.drop_index("idx_event_similarities_created_at", table_name="event_similarities")
    op.drop_table("event_similarities")
    op.drop_index(
        op.f("ix_correlation_rules_tenant_id"), table_name="correlation_rules"
    )
    op.drop_index(op.f("ix_correlation_rules_name"), table_name="correlation_rules")
    op.drop_index(
        "idx_correlation_rules_enabled_priority", table_name="correlation_rules"
    )
    op.drop_table("correlation_rules")
    op.drop_index(op.f("ix_blocked_ips_value"), table_name="blocked_ips")
    op.drop_index(op.f("ix_blocked_ips_is_active"), table_name="blocked_ips")
    op.drop_index(op.f("ix_blocked_ips_alert_id"), table_name="blocked_ips")
    op.drop_index("ix_blocked_ip_value_type", table_name="blocked_ips")
    op.drop_index("ix_blocked_ip_active_created", table_name="blocked_ips")
    op.drop_table("blocked_ips")
    op.drop_index(op.f("ix_assets_ip"), table_name="assets")
    op.drop_index(op.f("ix_assets_hostname"), table_name="assets")
    op.drop_index(op.f("ix_assets_deleted_at"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_ai_tasks_user_id"), table_name="ai_tasks")
    op.drop_index(op.f("ix_ai_tasks_task_type"), table_name="ai_tasks")
    op.drop_index(op.f("ix_ai_tasks_status"), table_name="ai_tasks")
    op.drop_table("ai_tasks")
    op.drop_index(op.f("ix_ai_models_provider"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_is_default"), table_name="ai_models")
    op.drop_table("ai_models")
    # ### end Alembic commands ###
