"""Add monitor_history table for persistent metrics storage

Revision ID: v0_7_8_monitor_history
Revises: e8521c2c56f4
Create Date: 2026-02-16 16:06:53

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'v0_7_8_monitor_history'
down_revision: Union[str, None] = 'e8521c2c56f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_history',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('cpu_percent', sa.Float(), nullable=False),
        sa.Column('memory_percent', sa.Float(), nullable=False),
        sa.Column('memory_used_gb', sa.Float(), nullable=False),
        sa.Column('memory_total_gb', sa.Float(), nullable=False),
        sa.Column('disk_percent', sa.Float(), nullable=False),
        sa.Column('disk_used_gb', sa.Float(), nullable=False),
        sa.Column('disk_total_gb', sa.Float(), nullable=False),
        sa.Column('services', sa.JSON(), nullable=False),
        sa.Column('requests_per_minute', sa.Integer(), nullable=False),
        sa.Column('error_rate', sa.Float(), nullable=False),
        sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitor_history_timestamp', 'monitor_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_monitor_history_timestamp'), 'monitor_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_history_timestamp'), table_name='monitor_history')
    op.drop_index('idx_monitor_history_timestamp', table_name='monitor_history')
    op.drop_table('monitor_history')
    # ### end Alembic commands ###
