"""Add event correlation tables for intelligent alert grouping

Revision ID: v0_8_0_event_correlation
Revises: v0_7_8_monitor_history
Create Date: 2026-02-16

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "v0_8_0_event_correlation"
down_revision: Union[str, None] = "v0_7_8_monitor_history"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create correlation_rules table
    op.create_table(
        "correlation_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("is_builtin", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column(
            "time_window_seconds", sa.Integer(), nullable=False, server_default="300"
        ),
        sa.Column("entity_types", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("min_similarity", sa.Float(), nullable=False, server_default="0.7"),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column(
            "action", sa.String(length=50), nullable=False, server_default="aggregate"
        ),
        sa.Column("action_params", sa.JSON(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="50"),
        sa.Column("group_by_field", sa.String(length=100), nullable=True),
        sa.Column(
            "total_correlations", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("last_triggered", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("updated_at", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_correlation_rules_name", "correlation_rules", ["name"], unique=False
    )
    op.create_index(
        "idx_correlation_rules_enabled_priority",
        "correlation_rules",
        ["enabled", "priority"],
        unique=False,
    )

    # Create correlated_events table
    op.create_table(
        "correlated_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("attack_type", sa.String(length=100), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("raw_event_ids", sa.JSON(), nullable=False),
        sa.Column("raw_event_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("common_entities", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("first_seen", sa.String(length=50), nullable=False),
        sa.Column("last_seen", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=50), nullable=False, server_default="open"
        ),
        sa.Column("assigned_to", sa.String(length=100), nullable=True),
        sa.Column("tactics", sa.JSON(), nullable=True),
        sa.Column("techniques", sa.JSON(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("ai_remediation", sa.Text(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=False, server_default="50.0"),
        sa.Column("affected_assets", sa.JSON(), nullable=True),
        sa.Column("affected_users", sa.JSON(), nullable=True),
        sa.Column("business_impact", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("updated_at", sa.String(length=50), nullable=False),
        sa.Column("resolved_at", sa.String(length=50), nullable=True),
        sa.Column("correlation_time_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["rule_id"], ["correlation_rules.id"]),
    )
    op.create_index(
        "idx_correlated_events_rule_id", "correlated_events", ["rule_id"], unique=False
    )
    op.create_index(
        "idx_correlated_events_status_severity",
        "correlated_events",
        ["status", "severity"],
        unique=False,
    )
    op.create_index(
        "idx_correlated_events_first_seen",
        "correlated_events",
        ["first_seen"],
        unique=False,
    )
    op.create_index(
        "idx_correlated_events_attack_type",
        "correlated_events",
        ["attack_type"],
        unique=False,
    )

    # Create event_similarities table
    op.create_table(
        "event_similarities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id_1", sa.String(length=100), nullable=False),
        sa.Column("event_id_2", sa.String(length=100), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("ttl_seconds", sa.Integer(), nullable=False, server_default="3600"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_event_similarities_event_pair",
        "event_similarities",
        ["event_id_1", "event_id_2"],
        unique=False,
    )
    op.create_index(
        "idx_event_similarities_created_at",
        "event_similarities",
        ["created_at"],
        unique=False,
    )

    # Create root_cause_analyses table
    op.create_table(
        "root_cause_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.String(length=100), nullable=False),
        sa.Column("root_cause_category", sa.String(length=50), nullable=False),
        sa.Column("root_cause_subcategory", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("reasoning_steps", sa.JSON(), nullable=False),
        sa.Column("evidence_chain", sa.JSON(), nullable=False),
        sa.Column("verification_steps", sa.JSON(), nullable=False),
        sa.Column("suggested_remediation", sa.Text(), nullable=True),
        sa.Column(
            "remediation_priority",
            sa.String(length=20),
            nullable=False,
            server_default="medium",
        ),
        sa.Column("similar_alerts", sa.JSON(), nullable=True),
        sa.Column("ai_model", sa.String(length=100), nullable=False),
        sa.Column("ai_prompt_version", sa.String(length=50), nullable=True),
        sa.Column("analysis_duration_ms", sa.Float(), nullable=True),
        sa.Column(
            "human_verified", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.Column("human_feedback", sa.Text(), nullable=True),
        sa.Column("feedback_category", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.String(length=50), nullable=False),
        sa.Column("updated_at", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_root_cause_alert_id", "root_cause_analyses", ["alert_id"], unique=False
    )
    op.create_index(
        "idx_root_cause_category",
        "root_cause_analyses",
        ["root_cause_category"],
        unique=False,
    )
    op.create_index(
        "idx_root_cause_confidence", "root_cause_analyses", ["confidence"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables in reverse order
    op.drop_table("root_cause_analyses")
    op.drop_table("event_similarities")
    op.drop_table("correlated_events")
    op.drop_table("correlation_rules")

    # ### end Alembic commands ###
