"""Add security alerts performance indexes and deduplication fields

Revision ID: v1_2_0_phase1_optimizations
Revises: v1_1_0_arch_upgrade
Create Date: 2026-02-26

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'v1_2_0_phase1_optimizations'
down_revision = 'v1_1_0_arch_upgrade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add deduplication and aggregation fields to security_alerts
    op.add_column('security_alerts', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('security_alerts', sa.Column('aggregated_count', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('security_alerts', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('security_alerts', sa.Column('is_aggregated', sa.Integer(), nullable=False, server_default='0'))
    
    # Create indexes for deduplication and aggregation
    op.create_index('ix_security_alerts_fingerprint', 'security_alerts', ['fingerprint'])
    op.create_index('ix_security_alerts_aggregated', 'security_alerts', ['is_aggregated'])
    
    # Additional composite indexes for security_alerts performance
    op.create_index(
        'ix_security_alerts_source_severity_created',
        'security_alerts',
        ['source', 'severity', sa.text('created_at DESC')]
    )
    
    op.create_index(
        'ix_security_alerts_status_created',
        'security_alerts',
        ['status', sa.text('created_at DESC')]
    )
    
    op.create_index(
        'ix_security_alerts_agent_name_created',
        'security_alerts',
        ['agent_name', sa.text('created_at DESC')]
    )
    
    op.create_index(
        'ix_security_alerts_source_ip_created',
        'security_alerts',
        ['source_ip', sa.text('created_at DESC')]
    )
    
    # Indexes for playbook_runs (additional optimization)
    op.create_index(
        'idx_playbook_run_trigger_time',
        'playbook_runs',
        ['trigger_id', sa.text('started_at DESC')]
    )
    
    # Indexes for audit_log
    op.create_index(
        'idx_audit_log_user_action',
        'audit_log',
        ['user_id', 'action', sa.text('created_at DESC')]
    )
    
    op.create_index(
        'idx_audit_log_resource',
        'audit_log',
        ['resource_type', 'resource_id', sa.text('created_at DESC')]
    )
    
    # Indexes for ioc_hits
    op.create_index(
        'idx_ioc_hits_type_value',
        'ioc_hits',
        ['ioc_type', 'ioc_value', sa.text('created_at DESC')]
    )
    
    op.create_index(
        'idx_ioc_hits_asset',
        'ioc_hits',
        ['asset_id', sa.text('created_at DESC')]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ioc_hits indexes
    op.drop_index('idx_ioc_hits_asset', table_name='ioc_hits')
    op.drop_index('idx_ioc_hits_type_value', table_name='ioc_hits')
    
    # Drop audit_log indexes
    op.drop_index('idx_audit_log_resource', table_name='audit_log')
    op.drop_index('idx_audit_log_user_action', table_name='audit_log')
    
    # Drop playbook_runs indexes
    op.drop_index('idx_playbook_run_trigger_time', table_name='playbook_runs')
    
    # Drop security_alerts indexes
    op.drop_index('ix_security_alerts_source_ip_created', table_name='security_alerts')
    op.drop_index('ix_security_alerts_agent_name_created', table_name='security_alerts')
    op.drop_index('ix_security_alerts_status_created', table_name='security_alerts')
    op.drop_index('ix_security_alerts_source_severity_created', table_name='security_alerts')
    op.drop_index('ix_security_alerts_aggregated', table_name='security_alerts')
    op.drop_index('ix_security_alerts_fingerprint', table_name='security_alerts')
    
    # Drop columns
    op.drop_column('security_alerts', 'is_aggregated')
    op.drop_column('security_alerts', 'last_seen_at')
    op.drop_column('security_alerts', 'aggregated_count')
    op.drop_column('security_alerts', 'fingerprint')
    # ### end Alembic commands ###
