"""Add alert deduplication and aggregation fields

Revision ID: v1_2_0_alert_deduplication
Revises: v1_1_0_arch_upgrade
Create Date: 2026-02-26

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "v1_2_0_alert_deduplication"
down_revision = "v1_1_0_arch_upgrade"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "security_alerts", sa.Column("fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "security_alerts",
        sa.Column("aggregated_count", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column(
        "security_alerts",
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "security_alerts",
        sa.Column("is_aggregated", sa.Integer(), nullable=False, server_default="0"),
    )

    # Create indexes
    op.create_index(
        "ix_security_alerts_fingerprint", "security_alerts", ["fingerprint"]
    )
    op.create_index(
        "ix_security_alerts_aggregated", "security_alerts", ["is_aggregated"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_security_alerts_aggregated", table_name="security_alerts")
    op.drop_index("ix_security_alerts_fingerprint", table_name="security_alerts")

    op.drop_column("security_alerts", "is_aggregated")
    op.drop_column("security_alerts", "last_seen_at")
    op.drop_column("security_alerts", "aggregated_count")
    op.drop_column("security_alerts", "fingerprint")
    # ### end Alembic commands ###
